### ISSUE TITLE
Push to non-master also triggers deploy

### ISSUE THREAD

**Issue by titouanc** [C4ptainCrunch/click-and-deploy#3]
In https://github.com/C4ptainCrunch/click-and-deploy/blob/master/web.py#L27-L32; there's no check for the POST payload when using click-and-deploy as GitHub webhook, resulting in undesired deployments

**Comment by C4ptainCrunch** [comment]
C'est fixé !
Le déploiement fonctionne toujours avec le clic, mais quand le header `X-GitHub-Event` est présent et vaut `push` click-and-deploy vérifie dans le payload que la branche est bien master.
Pour ça, il faut que le payload soit encodé en `application/json`
